Listen 443

<IfModule ssl_module>
    SSLSessionCache "shmcb:/run/httpd/ssl_scache(512000)"
    SSLSessionCacheTimeout 300

    <VirtualHost _default_:443>
        DocumentRoot "/work/repositorios"
        ServerName slackware-repositorio-local
        SSLEngine on
        SSLCertificateFile "/etc/httpd/repositorio.crt"
        SSLCertificateKeyFile "/etc/httpd/repositorio.key"

        <Directory "/work/repositorios">
            Options Indexes FollowSymLinks
            AllowOverride None
            Require all granted
        </Directory>
    </VirtualHost>
</IfModule>
